FROM doublelayer/docker-python-nodejs:python3.10-slim

WORKDIR /app

# Install Chrome dependencies
RUN apt-get -y update
RUN apt-get install -y chromium chromium-driver

# USER gitpod

# Add the Chrome as a path variable
ENV CHROME_BIN=/opt/chrome

COPY botasaurus-proxy /app/.

RUN pip install -r requirements.txt

CMD ["python", "server.py"]