FROM doublelayer/docker-python-nodejs

WORKDIR /app

# Install Chrome dependencies
RUN apt-get update && apt-get install -y unzip && \
    curl -Lo "/tmp/chromedriver.zip" "https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip" && \
    curl -Lo "/tmp/chrome-linux.zip" "https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Linux_x64%2F1135561%2Fchrome-linux.zip?alt=media" && \
    unzip /tmp/chromedriver.zip -d /opt/ && \
    unzip /tmp/chrome-linux.zip -d /opt/

RUN apt-get install -y atk cups-libs gtk3 libXcomposite alsa-lib \
    libXcursor libXdamage libXext libXi libXrandr libXScrnSaver \
    libXtst pango at-spi2-atk libXt xorg-x11-server-Xvfb \
    xorg-x11-xauth dbus-glib dbus-glib-devel tzdata

RUN rm -rf /var/lib/apt/lists/*

RUN cp -r /opt/chrome-linux /opt/chrome

COPY requirements.txt ./
RUN pip install -r requirements.txt

# USER gitpod

# Add the Chrome as a path variable
ENV CHROME_BIN=/opt/chrome

COPY botasaurus-proxy /app/.

RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "server.py"]